# Generated by Django 5.1.15 on 2025-12-25 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название магазина')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/', verbose_name='Логотип магазина')),
                ('website', models.URLField(blank=True, verbose_name='Сайт магазина')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название акции')),
                ('code', models.CharField(max_length=50, verbose_name='Промокод')),
                ('description', models.TextField(blank=True, verbose_name='Описание акции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='promocode.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ('-created_at',),
            },
        ),
    ]
