# Generated by Django 5.1.15 on 2026-01-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Группа промокодов',
                'verbose_name_plural': 'Группы промокодов',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='promo',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='promos', to='promocode.promogroup', verbose_name='Группы'),
        ),
    ]
